language: php

php:
    - "7.2"
    - "7.0"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1

before_script:
    - composer install

script:
    - composer run-script test
    - composer run-script lint
